services:
  - type: web
    name: shelter-analytics
    env: node
    plan: free
    buildCommand: |
      npm run build
      cd backend && pip3 install -r requirements.txt
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
    healthCheckPath: /api/health
    autoDeploy: true 